variable "region" {
  description = "The AWS region to deploy resources"
  type        = string
  default     = "eu-central-1"
}

variable "uploads_bucket_name" {
  description = "The name of the S3 bucket for file uploads"
  type        = string
  default     = "uploads-bucket"
}

variable "quarantine_bucket_name" {
  description = "The name of the S3 bucket for quarantined files"
  type        = string
  default     = "quarantine-bucket"
}

variable "environment" {
  description = "The environment for the deployment (e.g., dev, staging, prod)"
  type        = string
  default     = "prod"
}

variable "backend_certificate_arn" {
  description = "The ARN of the ACM certificate for the ALB HTTPS listener and API Gateway"
  type        = string
}

variable "api_image_upload_domain_name" {
  description = "The domain name for the API to get pre-signed image upload URLs"
  type        = string
  default     = "api-image-upload.epic-trip-planner.com"
}

variable "lambda_upload_presigned_url_expiration_time_s" {
  description = "Expiration time in seconds for the pre-signed URL generated by the upload Lambda function"
  type        = number
  default     = 300
}

variable "clamAV_layer_arn" {
  description = "The ARN of the ClamAV Lambda Layer"
  type        = string
  default     = "arn:aws:lambda:eu-central-1:387836084035:layer:ClamAVLayer:1"

}