variable "region" {
  description = "The AWS region to deploy resources"
  type        = string
  default     = "eu-central-1"
}

variable "route53_zone_name" {
  description = "Route 53 zone name (e.g., epic-trip-planner.com)"
  type        = string
}

variable "uploads_bucket_name" {
  description = "The name of the S3 bucket for file uploads"
  type        = string
  default     = "uploads-bucket"
}

variable "secret_store_name" {
  description = "Name of the secret store where API_GW_AUTH_SECRET value can be fetched"
  type        = string
}

variable "enable_transfer_acceleration" {
  type        = bool
  description = "Enable S3 Transfer Acceleration?"
  default     = false
}

variable "environment" {
  description = "The environment for the deployment (e.g., dev, staging, prod)"
  type        = string
  default     = "prod"
}

variable "backend_certificate_arn" {
  description = "The ARN of the ACM certificate"
  type        = string
}

variable "api_file_upload_domain_name" {
  description = "The domain name for the API to get pre-signed file upload URLs"
  type        = string
  default     = "api-file-upload.epic-trip-planner.com"
}

variable "lambda_upload_presigned_url_expiration_time_s" {
  description = "Expiration time in seconds for the pre-signed URL generated by the upload Lambda function"
  type        = number
  default     = 300
}

variable "use_bucketav" {
  description = "Use BucketAV to prevent malware to be uploaded in S3 bucket"
  type        = bool
  default     = true
}

variable "bucketav_sns_findings_topic_name" {
  description = "Name of SNS topics where BucketAV publishes findings"
  type        = string
}

variable "lambda_memory_size_mb" {
  description = "Memory size in MB value for Lambda processing file which allow faster execution"
  type        = number
  default     = 512
}

variable "lambda_process_uploaded_file_dir" {
  description = "Path to built Lambda directory, including node_modules"
  type        = string
}